stages:
  - build
  - deploy

variables:
  DOCKER_REPO: gitlab.skyshi.com:5000/gilankpam/php-ci

build:
  image: docker:git
  stage: build
  services:
    - docker:dind
  script:
    - sh build-docker.sh

dev:
  image: gitlab.skyshi.com:5000/ansible
  stage: deploy
  only:
    - master
  script:
    - sh ansible.sh