image: docker:git

variables:
    DOCKER_DRIVER: overlay
    DOCKER_REPO: gitlab.skyshi.com:5000/gilankpam/php-ci

services:
    - docker:dind
build:
    stage: build
    script:
        - sh build-docker.sh