image: docker:git

services:
    - docker:dind

build:
    script:
        - docker build -t php-ci .
        - docker tag php-ci gitlab.skyshi.com:5000/gilankpam/php-ci
        - docker push gitlab.skyshi.com:5000/gilankpam/php-ci