stages:
  - build
  # - deploy

variables:
  DOCKER_DRIVER: overlay
  DOCKER_REPO: gitlab.skyshi.com:5000/gilankpam/php-ci

services:
  - docker:dind

build:
  image: docker:git
  stage: build
  script:
    - sh build-docker.sh

# dev:
#   stage: deploy
#   only:
#     - master
#   script:
#     - sh ansible.sh