- hosts: {{ HOST }}
  tasks:
    - name: login to registry
      file: docker login -e dev@abc.com -u deploy -p {{ REGISTRY_PASSWORD }} https://registry.skyshi.com
    
    - name: copy compose file
      copy: src=./docker-sompose.yml dest=/tmp/docker-compose.yml

    - name: run docker compose
      shell: docker-compose -f /tmp/docker-compose.yml -p {{ PROJECT_NAME }} up -d 
      environment:
        VERSION: {{ VERSION }}

    - name: remove docker-compose file
      file: path=/tmp/docker-compose.yml state=absent