- hosts: gitlab.skyshi.com
  remote_user: gilang
  tasks:
    
    - name: copy compose file
      copy: src=./docker-compose.yml dest=/tmp/docker-compose.yml

    - name: run compose
      shell: docker-compose -f /tmp/docker-compose.yml -p php-ci up -d
      environment:
        TAG: master-ca2868b8

    - name: remove docker-compose file
      file: path=/tmp/docker-compose.yml state=absent