- hosts: all
  environment:
    TAG: "{{ TAG }}"
  tasks:
    - name: Copy docker compose file
      copy:
        src: docker-compose.yml
        dest: /tmp/docker-compose.yml
    - name: Restart Services
      shell: docker-compose -p php-ci -f /tmp/docker-compose.yml up -d
    - name: Remove docker-compose
      file:
        path: /tmp/docker-compose.yml
        state: absent
